# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f6b3688b-c5ac-48ca-a081-99702783d2ec";
    fsType = "btrfs";
    options = ["subvol=@" "noatime" "compress=zstd"];
  };

  boot.initrd.luks.devices."nixos".device = "/dev/disk/by-uuid/ae76fc22-682f-4b2c-ad18-29ac384745ae";
  boot.initrd.luks.devices."nixos".allowDiscards = true;

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/f6b3688b-c5ac-48ca-a081-99702783d2ec";
    fsType = "btrfs";
    options = ["subvol=@home" "noatime" "compress=zstd"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/f6b3688b-c5ac-48ca-a081-99702783d2ec";
    fsType = "btrfs";
    options = ["subvol=@nix" "noatime" "compress=zstd"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/f6b3688b-c5ac-48ca-a081-99702783d2ec";
    fsType = "btrfs";
    options = ["subvol=@log" "noatime" "compress=zstd"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/845D-CCDB";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
